name: Calendly-Pipeline

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        working-directory: app
        run: pip install -r requirements.txt

      - name: Run tests
        working-directory: app
        run: pytest